version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - model
    environment:
      - ENV_VAR_NAME=production
      - API_URL=http://backend:5000
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - ENV_VAR_NAME=production
      - API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  model:
    build: ./model
    environment:
      - ENV_VAR_NAME=production
      - MODEL_PATH=/app/models
    volumes:
      - ./model:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
