version: '3.8'

services:
  data-collection:
    build:
      context: ./data_collection
      dockerfile: Dockerfile
    container_name: sniffai-data-collection
    volumes:
      - ./data_collection:/app
    networks:
      - sniffai-network

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: sniffai-model
    volumes:
      - ./model:/app
    networks:
      - sniffai-network
    environment:
      - MODEL_ENV=production  # Example environment variable

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sniffai-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - sniffai-network
    depends_on:
      - model
      - data-collection
    environment:
      - BACKEND_ENV=development  # Example environment variable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sniffai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - sniffai-network
    depends_on:
      - backend

networks:
  sniffai-network:
    driver: bridge
