name: Build and Push Docker Images with Docker Compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      working-directory: ${{ github.workspace }}
      run: |
        if [ ! -f "docker-compose.yml" ]; then
          echo "Error: docker-compose.yml not found"
          exit 1
        fi
        docker-compose build
        docker-compose push